### ISSUE TITLE
Vault item creation triggers data bag deprecation warning

### ISSUE THREAD

**Issue by sirosen** [chef/chef-vault#215]
Knife added deprecation warnings for a number of methods depending on `json_class` loading behaviors.
In particular, these warnings: https://github.com/chef/chef/commit/0ef0ab07531ae78cb4052242037227b0fb5365dc

It seems that chef-vault is using an older method for instantiating a data bag item, relying on the automagic class determination logic of `json_class`.
By way of example, a simple `knife vault create` can trigger this warning:

```shell
$ knife vault create my_vault test_item
WARN: Auto inflation of JSON data is deprecated. Please pass in the class to inflate or use #edit_hash at /home/sirosen/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/forwardable.rb:183:in `edit_data'
```

Unfortunately that message isn't terribly useful thanks to `forwardable`, but the basic point is that `knife vault create ...` succeeds with a warning right now.

Before I'm asked:
ruby `2.2.1`, chef-dk `0.15.15`, chef-vault `2.9.0`

According to #chef on freenode (@coderanger in particular), `chef-vault` probably needs to update to use `Chef::DataBagItem.load` somewhere.

**Comment by northrup** [comment]
Any update on this? I just ran into this today.

**Comment by tiago-cruz-movile** [comment]
Is this warning related?

- Environment

```
$ chef -v
Chef Development Kit Version: 1.3.40
chef-client version: 12.19.36
delivery version: master (69bfa4a76959a8d093511a90fddd7a1f7e43e354)
berks version: 5.6.4
kitchen version: 1.16.0
```
- Create

```
$ knife vault create gandalf secrets -S "name:zabbix3"
WARN: Auto inflation of JSON data is deprecated. Please pass in the class to inflate or use #edit_hash (CHEF-1) at /opt/chefdk/embedded/lib/ruby/2.3.0/forwardable.rb:189:in `edit_data'.
Please see https://docs.chef.io/deprecations_json_auto_inflate.html for further details and information on how to correct this problem.
```

- Edit

```
$ knife vault edit gandalf secrets 
WARN: Auto inflation of JSON data is deprecated. Please pass in the class to inflate or use #edit_hash (CHEF-1) at /opt/chefdk/embedded/lib/ruby/2.3.0/forwardable.rb:189:in `edit_data'.
Please see https://docs.chef.io/deprecations_json_auto_inflate.html for further details and information on how to correct this problem.
```

**Comment by tiago-cruz-movile** [comment]
Same problem with chef-client 12.21.26:

```
tiagocruz@konoha:~/chef-repo/cookbooks/varnish$ chef -v
Chef Development Kit Version: 1.6.11
chef-client version: 12.21.26
delivery version: master (73ebb72a6c42b3d2ff5370c476be800fee7e5427)
berks version: ERROR
kitchen version: 1.16.0
inspec version: 1.25.1
tiagocruz@konoha:~/chef-repo/cookbooks/varnish$ knife vault create yyy xxx
WARN: Auto inflation of JSON data is deprecated. Please pass in the class to inflate or use #edit_hash (CHEF-1) at /opt/chefdk/embedded/lib/ruby/2.3.0/forwardable.rb:204:in `edit_data'.
Please see https://docs.chef.io/deprecations_json_auto_inflate.html for further details and information on how to correct this problem.
```

How can I fix this?
