### ISSUE TITLE
OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key: nested asn1 error

### ISSUE THREAD

**Issue by svanharmelen** [chef/chef-vault#230]
I notice that when I try to create a vault using the latest code in `master`, I get these errors:

```ruby
ERROR: OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key: nested asn1 error
```

Is there anything changed that is not backwards compatible? We're using `knife` version 2.13.37 against a 12.2.0 Chef server.

See here some output (I included the output of `git status` and `git log | head -1` so you can see the commit I'm using):

```
sander@svhadm01:/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0$ git status
# On branch master
nothing to commit (working directory clean)
sander@svhadm01:/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0$ git log | head -1
commit 00cda89286dead02c019cae6b97f501f59e299ad
sander@svhadm01:/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0$ knife vault create test test '{"test": "test"}' -A "svanharmelen" -S "name:svhadm01" -M client -VV
INFO: Using configuration from /home/sander/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as svanharmelen
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://betachef.schubergphilis.com/organizations/svh/data/test/test_keys
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-Ops-Server-API-Version: 1
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
DEBUG: X-OPS-USERID: svanharmelen
DEBUG: X-OPS-TIMESTAMP: 2016-10-06T15:58:48Z
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
DEBUG: X-OPS-AUTHORIZATION-1: rcqsDe6kkY77EAYUBORPLzgFEkSHnoa+CX/QpCK9DbWlzyuXsuvShF4B4jjb
DEBUG: X-OPS-AUTHORIZATION-2: AtHpQ0/t+M84pnI8k9LzGAaMGmSRq65H8IdOydX1RDckNVyHkpIB/zv5R/b7
DEBUG: X-OPS-AUTHORIZATION-3: toyvxPZqfheFm7kUnXc5VgpWuCvJERWhF5mD9Lw1Y5N0QBJMQ8MdmNQIo9+E
DEBUG: X-OPS-AUTHORIZATION-4: 1l0bMeI3UfqEhIjJPI8QT0/qTTlgZ2hnNo+qNt86UfgFMH9e7KVv3YlqbNtk
DEBUG: X-OPS-AUTHORIZATION-5: /Jii4aJKwP+pWuI7Zx/0hSYTTrbcnWvg7CjRbjuXnzn9PBNIQ0prlfenP1/C
DEBUG: X-OPS-AUTHORIZATION-6: RvZPHxHXbW6NncJYD0N1f1WgP4Tt4SIU9crxloSO6g==
DEBUG: HOST: betachef.schubergphilis.com:443
DEBUG: X-REMOTE-REQUEST-ID: 3e555f3d-1c13-4a97-ab10-885564938bbc
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 404 Not Found
DEBUG: server: openresty/1.7.10.1
DEBUG: date: Thu, 06 Oct 2016 15:59:39 GMT
DEBUG: content-type: application/json
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=12.2.0
DEBUG: x-ops-server-api-version: {"min_version":"0","max_version":"1","request_version":"1","response_version":"1"}
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: ---- HTTP Response Body ----
DEBUG:VJ-*RVrNQOLQHI,ITHJLWI(I-.,VHBȁbkfpC
DEBUG: ---- End HTTP Response Body -----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot identify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
INFO: HTTP Request Returned 404 Not Found: Cannot load data bag item test_keys for data bag test
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as svanharmelen
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://betachef.schubergphilis.com/organizations/svh/search/node?q=name:svhadm01&sort=X_CHEF_id_CHEF_X%20asc&start=0
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-Ops-Server-API-Version: 1
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
DEBUG: X-OPS-USERID: svanharmelen
DEBUG: X-OPS-TIMESTAMP: 2016-10-06T15:58:48Z
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
DEBUG: X-OPS-AUTHORIZATION-1: LdHUTZg1nmXZgILLM23Qvm38/JmLZN5jqwK604YlGzfSMwbyM6vmqYaPRHDh
DEBUG: X-OPS-AUTHORIZATION-2: O7TQRZw41SKqTBX0nNxXb5oX7Ctvo0ic3CIFRt6vdsektJFBLrLPk1GW7Uvm
DEBUG: X-OPS-AUTHORIZATION-3: dR97N2nPZDxGAXYEgm7gHG9jFXC7sY7wJcGICIDbBN4YjcQKRNzQEQrG7IWg
DEBUG: X-OPS-AUTHORIZATION-4: 8fTcByHvIlK9652oHS2xhYGchLj6JZxH4r0Z5nw4XQpNlLzsUmgOVemPJfoy
DEBUG: X-OPS-AUTHORIZATION-5: UUN9gGvUJh+Cewb+y0n9g8dSgrzBIUS1iM5RkSJeRDWGodXFqt7TarGsVNSy
DEBUG: X-OPS-AUTHORIZATION-6: 5KhzoioZRJU3H5ioWCuXHqI/HCIk3UxB3pvslrKcTQ==
DEBUG: HOST: betachef.schubergphilis.com:443
DEBUG: X-REMOTE-REQUEST-ID: 3e555f3d-1c13-4a97-ab10-885564938bbc
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: server: openresty/1.7.10.1
DEBUG: date: Thu, 06 Oct 2016 15:59:39 GMT
DEBUG: content-type: application/json
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=12.2.0
DEBUG: x-ops-server-api-version: {"min_version":"0","max_version":"1","request_version":"1","response_version":"1"}
DEBUG: x-content-type-options: nosniff
DEBUG: x-xss-protection: 1; mode=block
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot identify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_request
DEBUG: Signing the request as svanharmelen
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://betachef.schubergphilis.com/organizations/svh/clients/svhadm01/keys/default
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-Ops-Server-API-Version: 1
DEBUG: X-OPS-SIGN: algorithm=sha1;version=1.1;
DEBUG: X-OPS-USERID: svanharmelen
DEBUG: X-OPS-TIMESTAMP: 2016-10-06T15:58:48Z
DEBUG: X-OPS-CONTENT-HASH: 2jmj7l5rSw0yVb/vlWAYkK/YBwk=
DEBUG: X-OPS-AUTHORIZATION-1: Tn2AJh5FJmnCPzcBgL4aVZkUpqNU3sLbk7o8dNC1pb7GxZVqZpvsNkkUTMQW
DEBUG: X-OPS-AUTHORIZATION-2: VPqUl9CFH+MHGcETHo/OMWmCB/PinRfQlwMU6IihHCBY8ADxNQVoGMr9KyL5
DEBUG: X-OPS-AUTHORIZATION-3: jkV6CiFUI5pSo0eBXLoLxN38Ogns0/5N9nn/szD3KW4VnpNd1lpTj4bDo+ba
DEBUG: X-OPS-AUTHORIZATION-4: MPo+y9BJGlbaITYVnwe5piE6H4+kS1f1AHtRPOTLij1sVVGfSwknVWyYNnJB
DEBUG: X-OPS-AUTHORIZATION-5: +QEXt+JBEKzVNPXQ3z1S5/0nYdYKVqCRHyEwdL5oURprO1sJejDNsf4l2+5Y
DEBUG: X-OPS-AUTHORIZATION-6: tAEDwI6AV+/vDq/6ZrY5+WdgomDqBGsc7uCt7LP86w==
DEBUG: HOST: betachef.schubergphilis.com:443
DEBUG: X-REMOTE-REQUEST-ID: 3e555f3d-1c13-4a97-ab10-885564938bbc
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 200 OK
DEBUG: server: openresty/1.7.10.1
DEBUG: date: Thu, 06 Oct 2016 15:59:39 GMT
DEBUG: content-type: application/json
DEBUG: transfer-encoding: chunked
DEBUG: connection: close
DEBUG: x-ops-api-info: flavor=cs;version=12.0.0;oc_erchef=12.2.0
DEBUG: x-ops-server-api-version: {"min_version":"0","max_version":"1","request_version":"1","response_version":"1"}
DEBUG: x-content-type-options: nosniff
DEBUG: x-xss-protection: 1; mode=block
DEBUG: content-encoding: gzip
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: HTTP server did not include a Content-Length header in response, cannot identify truncated downloads.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Authenticator#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Decompressing gzip response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
/opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0/lib/chef-vault/item_keys.rb:133:in `initialize': Neither PUB key nor PRIV key: nested asn1 error (OpenSSL::PKey::RSAError)
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0/lib/chef-vault/item_keys.rb:133:in `new'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0/lib/chef-vault/item_keys.rb:133:in `encode_key'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0/lib/chef-vault/item_keys.rb:43:in `add'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0/lib/chef-vault/item.rb:454:in `add_client'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0/lib/chef-vault/item.rb:90:in `block in clients'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/search/query.rb:90:in `block in search'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/search/query.rb:90:in `each'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/search/query.rb:90:in `search'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0/lib/chef-vault/item.rb:84:in `clients'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0/lib/chef/knife/vault_create.rb:84:in `rescue in run'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-vault-2.9.0/lib/chef/knife/vault_create.rb:57:in `run'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/knife.rb:421:in `block in run_with_pretty_exceptions'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/local_mode.rb:44:in `with_server_connectivity'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/knife.rb:420:in `run_with_pretty_exceptions'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/knife.rb:219:in `run'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/lib/chef/application/knife.rb:156:in `run'
        from /opt/chef/embedded/lib/ruby/gems/2.1.0/gems/chef-12.13.37/bin/knife:25:in `<top (required)>'
        from /usr/local/bin/knife:23:in `load'
        from /usr/local/bin/knife:23:in `<main>'
```

**Comment by thommay** [comment]
Hmm. I just tried this with master of chef-vault against a freshly created 12.2.0 chef server and can't reproduce the problem. 

what do you get from
```
knife raw https://betachef.schubergphilis.com/organizations/svh/clients/svhadm01/keys/default
```

**Comment by svanharmelen** [comment]
I tried to reproduce this on a bunch of other machines, but also could not reproduce it. So there is exactly one machine that gives me this error. And looking closer this seems a pretty old machine running Ubuntu 10.04, so my guess is it's the machine and not this code (thankfully).

Sorry for the noise on this one...

**Comment by thommay** [comment]
No problem at all; thanks for the report and for testing :)

**Comment by rbugajewski** [comment]
I had a similar error, but only when I tried to create new vault items (list / edit worked). Thanks @thommay for pointing me in the right direction and giving an example of the raw response. This way I figured out that Chef Server stored an old certificate. The [official chef-vault docs](https://docs.chef.io/chef_vault.html) actually say that this configuration isn’t supported anymore and that you have to regenerate private/public keypairs for all nodes. I had to do it for an admin user, so I logged in to the Chef Manage and created a new keypair, then replaced it in the `.chef` folder on my workstation. Another `knife raw` request for verification purposes showed the public key instead of the old certificate this time. Everything works again 👍

HTH other people in similar circumstances.

**Comment by lightener** [comment]
@rbugajewski Would love some direction on this. Trying to set up a new vault item and I keep getting this error. What steps do I need to take to resolve it? I was reading the doc you linked, still not very clear.
