### ISSUE TITLE
chef-vault standalone with solo

### ISSUE THREAD

**Issue by rahulsh1** [chef/chef-vault#260]
I created a databag created using `knife vault` commands. Now I want to retrieve the items from the databag using the standalone binary in mode 'solo'.  When I run this, it attempts to connect to a URL instead. Using chef-solo version 12.6.0.
    
    $ chef-vault -k /home/vagrant/.chef/knife.rb -v myvault -i root -a username
    [2017-03-04T10:59:34-08:00] ERROR: Connection refused connecting to https://localhost/data/myvault/root_keys, retry 1/5
    [2017-03-04T10:59:39-08:00] ERROR: Connection refused connecting to https://localhost/data/myvault/root_keys, retry 2/5
    ^C/home/vagrant/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/chef-12.6.0/lib/chef/http.rb:330:in `sleep': Interrupt
    	from /home/vagrant/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/chef-12.6.0/lib/chef/http.rb:330:in `rescue in retrying_http_errors'
    	from /home/vagrant/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/chef-12.6.0/lib/chef/http.rb:304:in `retrying_http_errors'
    	from /home/vagrant/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/chef-12.6.0/lib/chef/http.rb:269:in `send_http_request'
    	from /home/vagrant/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/chef-12.6.0/lib/chef/http.rb:144:in `request'
    	from /home/vagrant/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/chef-12.6.0/lib/chef/rest.rb:120:in `get'
    	from /home/vagrant/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/chef-12.6.0/lib/chef/data_bag_item.rb:152:in `load'
    	from /home/vagrant/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/chef-vault-2.9.1/lib/chef-vault/item_keys.rb:116:in `load'
    	from /home/vagrant/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/chef-vault-2.9.1/lib/chef-vault/item.rb:73:in `load_keys'
    	from /home/vagrant/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/chef-vault-2.9.1/lib/chef-vault/item.rb:268:in `load'
    	from /home/vagrant/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/chef-vault-2.9.1/bin/chef-vault:90:in `<top (required)>'
    	from /home/vagrant/.rbenv/versions/2.2.4/bin/chef-vault:23:in `load'
    	from /home/vagrant/.rbenv/versions/2.2.4/bin/chef-vault:23:in `<main>' 

Here is my knife.rb

    $ cat /home/vagrant/.chef/knife.rb
      knife[:vault_mode] = 'solo'
      data_bag_path "/home/vagrant/chefvault/databags"
      client_key "/home/vagrant/chefvault/key.pem"

What am I missing here?

**Comment by rahulsh1** [comment]
nm, I was missing the solo entry in the knife.rb. After adding that, it worked
