### ISSUE TITLE
Can't create chef vault items in solo mode

### ISSUE THREAD

**Issue by sanga1794** [chef/chef-vault#376]
# Scenario:
This command works fine on Chef Workstation version: 0.15.18 but at some point it looks like solo mode was broken. This seems to have broken in a similar way that it has in the past. see chef/chef-vault#203. Does the Net::HTTPServerException also need to be rescued here?
```
knife vault create r101_gitlab_runner project_token '{"id": "project_token", "key": "REDACTED"}' -S "role:*r101*gitlab_runner* OR cookbooks:r101_gitlab_runner" -A "rdean,eswells,ecottom,cradice,agiard,eddiep,vmod_s
vc" -M solo -VVV
INFO: Using configuration from /mnt/d/chef-repo/.chef/config.rb
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-vault-4.1.0/lib/chef-vault/item_keys.rb:237:in `rescue in load': uninit
ialized constant Net::HTTPServerException (NameError)
 from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-vault-4.1.0/lib/chef-vault/item_keys.rb:235:in `load'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-vault-4.1.0/lib/chef-vault/item.rb:79:in `load_keys'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-vault-4.1.0/lib/chef-vault/item.rb:291:in `load'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-vault-4.1.0/lib/chef/knife/vault_create.rb:71:in `run'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/knife-17.3.13/lib/chef/knife.rb:494:in `block in run_with_prett
y_exceptions'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.2.29/lib/chef/local_mode.rb:42:in `with_server_connecti
vity'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/knife-17.3.13/lib/chef/knife.rb:493:in `run_with_pretty_excepti
ons'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/knife-17.3.13/lib/chef/knife.rb:233:in `run'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/knife-17.3.13/lib/chef/application/knife.rb:165:in `run'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/knife-17.3.13/bin/knife:24:in `<top (required)>'
from /usr/bin/knife:365:in `load'
from /usr/bin/knife:365:in `<main>'
/opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.2.29/lib/chef/data_bag_item.rb:154:in `load': Item project_token_key
s not found in data bag r101_gitlab_runner. Other items found: (Chef::Exceptions::InvalidDataBagItemID)
 from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-vault-4.1.0/lib/chef-vault/item_keys.rb:236:in `load'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-vault-4.1.0/lib/chef-vault/item.rb:79:in `load_keys'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-vault-4.1.0/lib/chef-vault/item.rb:291:in `load'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-vault-4.1.0/lib/chef/knife/vault_create.rb:71:in `run'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/knife-17.3.13/lib/chef/knife.rb:494:in `block in run_with_prett
y_exceptions'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/chef-17.2.29/lib/chef/local_mode.rb:42:in `with_server_connecti
vity'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/knife-17.3.13/lib/chef/knife.rb:493:in `run_with_pretty_excepti
ons'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/knife-17.3.13/lib/chef/knife.rb:233:in `run'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/knife-17.3.13/lib/chef/application/knife.rb:165:in `run'
from /opt/chef-workstation/embedded/lib/ruby/gems/3.0.0/gems/knife-17.3.13/bin/knife:24:in `<top (required)>'
from /usr/bin/knife:365:in `load'
from /usr/bin/knife:365:in `<main>'
```

# Steps to Reproduce:
knife vault create r101_gitlab_runner project_token '{"id": "project_token", "key": "REDACTED"}' -S "role:r101gitlab_runner* OR cookbooks:r101_gitlab_runner" -A "rdean,eswells,ecottom,cradice,agiard,eddiep,vmod_s
vc" -M solo -VVV
# Expected Result:

Creates a new chef vault and item

# Actual Result:

ERROR: knife encountered an unexpected error

**Comment by sanga1794** [comment]
Closing this issue as https://github.com/chef/customer-bugs/issues/433#issuecomment-882720642.
